### ISSUE TITLE
Reihenfolge der Kurse & Ladebalken

### ISSUE THREAD

**Issue by fewohlgemuth** [CorrelAid/correlaidx-austria-education#2]
Die Kurse tauchen nicht in der richtigen chronologischen Reihenfolge auf und der Ladebalken verschwindet nicht. Eventuell ein Problem mit der "next" Datumsangabe in den Kursseiten.

**Comment by MisterXY89** [comment]
Spinner Problem ist mit commit [bf72954](https://github.com/CorrelAid/correlaidx-austria-education/commit/bf72954e4e730f68a86c3bd4a1b9f08da21e27f1) behoben.

Die Reihenfolge stimmt bei mir (latent Chrome App, Android)
